"""initial schema: users, snov_accounts, api_keys, audit_logs

Revision ID: 7e2022b48bd3
Revises: 
Create Date: 2026-08-11 09:18:53.236142

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7e2022b48bd3'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('ADMIN', 'OPERATOR', 'READONLY', name='user_role'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('api_keys',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('key_hash', sa.String(length=64), nullable=False),
    sa.Column('prefix', sa.String(length=16), nullable=False),
    sa.Column('scopes', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'REVOKED', name='api_key_status'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_api_keys_created_by_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_api_keys'))
    )
    op.create_index(op.f('ix_api_keys_key_hash'), 'api_keys', ['key_hash'], unique=True)
    op.create_index(op.f('ix_api_keys_status'), 'api_keys', ['status'], unique=False)
    op.create_table('snov_accounts',
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('snov_id', sa.String(length=255), nullable=False),
    sa.Column('snov_secret_encrypted', sa.Text(), nullable=False),
    sa.Column('snov_email_encrypted', sa.Text(), nullable=False),
    sa.Column('snov_password_encrypted', sa.Text(), nullable=False),
    sa.Column('snov_email_lookup_hash', sa.String(length=64), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', name='account_status'), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.Column('usage_count', sa.Integer(), nullable=False),
    sa.Column('assigned_to', sa.String(length=255), nullable=True),
    sa.Column('cooldown_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_snov_accounts_created_by_users')),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], name=op.f('fk_snov_accounts_updated_by_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_snov_accounts'))
    )
    op.create_index('ix_snov_accounts_active_lookup', 'snov_accounts', ['status', 'deleted_at'], unique=False)
    op.create_index('ix_snov_accounts_created_at', 'snov_accounts', ['created_at'], unique=False)
    op.create_index(op.f('ix_snov_accounts_email'), 'snov_accounts', ['email'], unique=True)
    op.create_index(op.f('ix_snov_accounts_snov_email_lookup_hash'), 'snov_accounts', ['snov_email_lookup_hash'], unique=True)
    op.create_index(op.f('ix_snov_accounts_status'), 'snov_accounts', ['status'], unique=False)
    op.create_table('audit_logs',
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('api_key_id', sa.UUID(), nullable=True),
    sa.Column('action', sa.Enum('LOGIN_SUCCESS', 'LOGIN_FAILED', 'ACCOUNT_CREATED', 'ACCOUNT_UPDATED', 'ACCOUNT_ACTIVATED', 'ACCOUNT_DEACTIVATED', 'ACCOUNT_DELETED', 'CREDENTIALS_ACCESSED', 'API_KEY_CREATED', 'API_KEY_REVOKED', name='audit_action'), nullable=False),
    sa.Column('resource', sa.String(length=64), nullable=False),
    sa.Column('resource_id', sa.String(length=255), nullable=True),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('user_agent', sa.String(length=512), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['api_key_id'], ['api_keys.id'], name=op.f('fk_audit_logs_api_key_id_api_keys')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_audit_logs_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_logs'))
    )
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_audit_logs_api_key_id'), 'audit_logs', ['api_key_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_user_id'), 'audit_logs', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_audit_logs_user_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_api_key_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_snov_accounts_status'), table_name='snov_accounts')
    op.drop_index(op.f('ix_snov_accounts_snov_email_lookup_hash'), table_name='snov_accounts')
    op.drop_index(op.f('ix_snov_accounts_email'), table_name='snov_accounts')
    op.drop_index('ix_snov_accounts_created_at', table_name='snov_accounts')
    op.drop_index('ix_snov_accounts_active_lookup', table_name='snov_accounts')
    op.drop_table('snov_accounts')
    op.drop_index(op.f('ix_api_keys_status'), table_name='api_keys')
    op.drop_index(op.f('ix_api_keys_key_hash'), table_name='api_keys')
    op.drop_table('api_keys')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###

    # op.drop_table() não remove os tipos ENUM do Postgres automaticamente — precisa dropar explicitamente.
    bind = op.get_bind()
    sa.Enum(name='audit_action').drop(bind, checkfirst=True)
    sa.Enum(name='account_status').drop(bind, checkfirst=True)
    sa.Enum(name='api_key_status').drop(bind, checkfirst=True)
    sa.Enum(name='user_role').drop(bind, checkfirst=True)
